---
# Install docker python package.
- name: Ensure python docker-py package is installed
  pip:
    name: docker-py

# Starts or restarts the container.
- name: Start/Restart the container
  docker_container:
    name: "fproject-{{ fproject_environment }}"
    image: "{{ fproject_image }}:{{ fproject_image_version }}"
    command: "{{ fproject_command }}"
    state: started
    ports:
     - "{{ fproject_host_port }}:{{ fproject_container_port }}"

# This checks that the container that is started.
- name: verify that webserver is running
  uri:
    url: "http://52.53.194.21:{{ fproject_host_port }}"
    method: GET
