---
# Install the docker service
- name: install docker dependencies
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    cache_valid_time: 1800
  with_items:
    - apt-transport-https
    - ca-certificates  
    - curl
    - software-properties-common

# Add docker's GPG key
- name: Setup docker repository key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify: apt-get update

# Determine what version of ubuntu is running

- name: Get release
  command: lsb_release -c -s
  register: release

# Here we add docker's repository to allow the system to do an apt-get install of
# official docker packages.
- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable
    state: present
    filename: docker
  notify: apt-get update

# Install the docker service.  Fix the name of the package.
- name: Install the latest version of docker community edition
  apt:
    pkg: docker-ce
    update_cache: yes
    cache_valid_time: 1800
